### ISSUE TITLE
Documentation about the goal of each extension

### ISSUE THREAD

**Issue by stof** [fabpot/sphinx-php#26]
it would be great to add a bit of documentation describing the goal of each extension and how they are meant to be used.
I know about `sensio.sphinx.configurationblock` (providing the `configuration-block` directive) and `sensio.sphinx.phpcode` (providing the `namespace`, `class`, `method`, `phpclass`, `phpmethod` and `phpfunc` roles) thanks to their heavy usage in the Symfony documentation, and so I could probably write some explanations about them.
However, `sensio.sphinx.bestpractice` (with its `bestpractice` directive) is less clear to me (is it just about providing a special kind of containers or is there some specificity ?) and I have no idea what `sensio.sphinx.php` (not even listed in the readme) and `sensio.sphinx.refinclude` are about.

**Comment by MantasVaitkunas** [comment]
:+1:

**Comment by hassankhan** [comment]
:+1:
