### ISSUE TITLE
Warnings with parameters in yaml-blocks.

### ISSUE THREAD

**Issue by temp** [fabpot/sphinx-php#32]
Example:
```
.. code-block:: yaml

    test: %my_parameter%
```

Results in:
```
WARNING: Could not parse literal_block as "yaml". highlighting skipped.
```

**Comment by lyrixx** [comment]
IIRC, you have to surround the value with double quote `"` because it contains `%`

**Comment by temp** [comment]
You don't have to. At least in symfony 2.8 there is no error if you omit the double quotes.
And what if the parameter is an integer? Will this have implications if I use double quotes?

**Comment by lyrixx** [comment]
See Example 5.10. Invalid use of Reserved Indicators in http://yaml.org/spec/1.2/spec.html

**Comment by xabbuh** [comment]
Indeed, and starting with Symfony 3.1 this is also deprecated (see symfony/symfony#17809) and will be removed in Symfony 4.0.

**Comment by temp** [comment]
Ok, thanks for the info!
