### ISSUE TITLE
request document for quick start to use the package

### ISSUE THREAD

**Issue by alochym01** [fabpot/sphinx-php#37]
hi list

i request the document for quick start of the package

i use sphinx to document of python project and all documents of api Controller  are docstring as 
```
:param arg1: description
:param arg2: description
:type arg1: type description
:type arg1: type description
:return: return description
:rtype: the return type description

:Example:

followed by a blank line !
```
and how to do the same with sphinx-php package

please give the example of the case

thank you

**Comment by fabpot** [comment]
Closing as this repository is not maintained anymore.
Symfony is now using a PHP parser: https://github.com/doctrine/rst-parser
