### ISSUE TITLE
Image Generated from matplotlib.sphinxext.mplmath   extension  has path not working on network

### ISSUE THREAD

**Issue by atulsingh7890** [fabpot/sphinx-php#7]
I have used matplot lib to generate mathematical symbols, and after build it works fine on local or even shared directory , when i try to access it through wamp by  putting the whole build directory in the www folder images are not showing which are generated from mplmath extension.

On further analysis i found that the image path which is added into the html genereted page was like this
<img class="center" src="../../_images\mathmpl/math-0c2c417359.png"

See the backslash between the images and mathmpl , it works fine in case of local of shared file. but on wamp it doesnt works.
It the above link is 
<img class="center" src="../../_images/mathmpl/math-0c2c417359.png"
it works fine.

**Comment by stof** [comment]
The matplotlib sphinx extension is not part of this repo. you should report it to the matplotlib team instead (or whoever maintains the matplotlib sphinx extension)

**Comment by lyrixx** [comment]
@fabpot this one could be closed.
